# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0c6fbfc4514f951e8a301c22f983415aeaf042b5b6dcf4e2884f9fab7239de858ac9b96a2c31c823b604b46a34316288eabf9c4bd4ae021ca925d856a23b9207

test:
  secret_key_base: 90792cf19570022ecef7e328a7533ef7b28fa7ba041e5931b2e757e5ef441a84defe339f4d0677d805dce1c772675cff22af13ba189342b27d10503d8f9664c1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
